# .github/workflows/sync.yml
name: Rebase Upstream
on:
  schedule:
  - cron: "5 16 * * *"  # run once a week
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10  # greater than the number of commits you made
    - uses: imba-tjd/rebase-upstream-action@master
      with:
        # <user>/<repo> or the full HTTP URL
        upstream: mycard/ygopro-database
        # The upstream branch that is rebased on
        branch: master
        # Do the force push in this action
        push: true
